---
- name: Install mandatory packages
  yum:
    name: "{{ packages.mandatory }}"
    state: latest

- name: Activate mandatory services
  service:
    name: "{{ item }}"
    enabled: true
    state: started
  with_items: "{{ services.mandatory }}"

- name: Install optional packages
  yum:
    name: "{{ packages.optional }}"
    state: latest
  tags:
    - optional_packages
